apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: roboshop
spec:
  #list of containers
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

#since no namespace is specified, the pod will be created in the default namespace.