apiVersion: v1
kind: Pod
metadata:
  name: dummy-pod-tester
 # namespace: roboshop-tester
spec:
  #list of containers
  containers:
  - name: dummy-pod-container
    image: nginx
    ports:
    - containerPort: 80 

#since no namespace is specified, the pod will be created in the default namespace.