apiVersion: v1
kind: Pod
metadata:
  name: labels-pod
  labels:  # it is a key:value pair which is used to identify the pod. It is used to group the pods and also used to select the pods.
    course: devops
    Trainer: SivaKumar_Reddy
spec:
   containers:
   - name: nginx
     image: nginx
     ports:
      - containerPort: 80 

   - name: almalinux
     image: almalinux:8
     command: ["sleep", "300"] #to avoud error as almalinux image does not have any default command to run and will give error by default. So we are providing a command to run in the container.