apiVersion: v1
kind: Pod
metadata:
  name: annotation-pod
  labels:  # it is a key:value pair which is used to identify the pod. It is used to group the pods and also used to select the pods.
    course: devops
    Trainer: SivaKumar_Reddy
  annotations:  # it is a key:value pair which is used to add metadata to the pod. It is used to store additional information about the pod.
    com.roboshop.training.duration: "120 hours"
    jenkins.url: "http://jenkins:8080/job/my-job/#45"
spec:
   containers:
   - name: nginx
     image: nginx
     ports:
      - containerPort: 80 

#we can put heavy information in annotations 